### ISSUE TITLE
.DS_Storeがあるとすごくダサい＞＜

### ISSUE THREAD

**Issue by okamuroshogo** [kyutechapp2017/server#21]
mac特有のファイル
.DS_Storeがリポジトリに含まれてしまっているっぽい

gitignoreを編集してくだされ

**Comment by KazuoY** [comment]
編集しました。

..っていうファイルは存在しても良いのですか？


ついでに言うと、#21付け忘れていました。

**Comment by okamuroshogo** [comment]
すでにリモートにpushされているものは、ignoreは反映されません！！
コマンドを調べる出てきます

もう一ついうと、スクレイピングのwipでやるよりdevelopで作業して欲しかった！（今回は良い）

**Comment by okamuroshogo** [comment]
@3000manJPY あああ、同じ編集内容を違うブランチでやりたいなら
cherry-picでやって欲しかった！！！！！

**Comment by 3000manJPY** [comment]
@okamuroshogo  github上でポチポチってやっちゃいました...

**Comment by okamuroshogo** [comment]
@3000manJPY lib/以下にも DS_Storeがあるから
一つづつ消すcommitよりも、コマンドでできるよん

**Comment by 3000manJPY** [comment]
@okamuroshogo ggりましたw
次から気をつけますm(_ _)m

**Comment by okamuroshogo** [comment]
っていうより、ダサいって感覚を持ってもらえば、
次は気持ち悪くてしょうがなくなるから大丈夫b
